stages:
  areas:
    wdir: ../..
    cmd: python pipelines/vacant-homes/areas.py
    deps:
      - pipelines/vacant-homes/areas.py
      - housingengland/AllCombined_Cleaned_2024_update.csv
    outs: 
      - src/visualisations/vacant-homes/_data/areas.json:
          cache: false